<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<title>Teacher Manage School Equipment</title>
<link rel="stylesheet" type="text/css"
	href="assets/css/style_manageuser.css">
</head>
<body>
	<div class="container">
		<!-- Sidebar -->
		<div class="sidebar">
			<div class="profile">
				<img src="assets/images/icon_teacher.png" alt="Profile Picture"
					class="profile-pic">
				<div class="profile-pic">
					<h3>Teacher</h3>
					<p>hairulsmkmr@gov.my</p>
				</div>
			</div>

			<button class="logout-btn" onclick="window.location.href='login.jsp'">Log
				Out</button>
			<hr>
			<ul class="nav">
				<li><a href="dashboard_teacher.jsp">Dashboard</a></li>
				<li><a href="school_info_teacher.jsp">School Information</a></li>
				<li><a href="#">School Version</a></li>
				<li><a href="school_equipment_teacher.jsp" class="active">Equipment
						Information</a></li>
				<li><a href="manage_user_teacher.jsp">Manage User
						Information</a></li>
				<li><a href="crew_application_teacher.jsp">Crew
						Application</a></li>
			</ul>
		</div>

		<!-- Main Content -->
		<div class="dashboard-content">
			<!-- Add Model Button -->
			<button class="add-model-btn"
				onclick="window.location.href='add_school_equipment_teacher.jsp'">Add
				Model</button>

			<div class="header">
				<img src="assets/images/kpm_logo.png" alt="KPM Logo" class="logo">
				<h2>TVPSS Management System</h2>
			</div>

			<!-- Search and Add User -->
			<div class="search-bar">
				<input type="text" id="searchName" placeholder="Search school...">
				<button onclick="searchUser()">Search</button>
				<!-- Add User Button -->
			</div>

			<!-- User Table -->
			<table class="user-table">
				<thead>
					<tr>
						<th>Model</th>
						<th>Type of Model</th>
						<th>Status</th>
						<th>Actions</th>
					</tr>
				</thead>
				<!-- User Table -->
				<tbody id="userList">
					<!-- Example row, dynamically generated by JS -->
					<tr>
						<td>Nikon D850 Camera</td>
						<td>Camera</td>
						<td>Work</td>
						<td>
							<div class="table-action-buttons">
								<!-- Edit Form -->
								<form action="SchoolEquipment_teacher" method="post"
									style="display: inline;">
									<input type="hidden" name="action" value="edit"> <input
										type="hidden" name="id" value="1">
									<button class="edit" type="submit">Edit</button>
								</form>
								<!-- Delete Form -->
								<form action="SchoolEquipment_teacher" method="post"
									style="display: inline;">
									<input type="hidden" name="action" value="delete"> <input
										type="hidden" name="id" value="1">
									<button class="delete" type="submit">Delete</button>
								</form>
							</div>
						</td>
					</tr>
					<tr>
						<td>Microphone Shure Sm58</td>
						<td>Microphone</td>
						<td>Damage</td>
						<td>
							<div class="table-action-buttons">
								<!-- Edit Form -->
								<form action="SchoolEquipment_teacher" method="post"
									style="display: inline;">
									<input type="hidden" name="action" value="edit"> <input
										type="hidden" name="id" value="1">
									<button class="edit" type="submit">Edit</button>
								</form>
								<!-- Delete Form -->
								<form action="SchoolEquipment_teacher" method="post"
									style="display: inline;">
									<input type="hidden" name="action" value="delete"> <input
										type="hidden" name="id" value="1">
									<button class="delete" type="submit">Delete</button>
								</form>
							</div>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<script>
		function searchUser() {
			var input = document.getElementById("searchName").value
					.toLowerCase();
			var rows = document.querySelectorAll("#userList tr");

			rows.forEach(function(row) {
				var name = row.querySelector("td").textContent.toLowerCase();
				if (name.includes(input)) {
					row.style.display = "";
				} else {
					row.style.display = "none";
				}
			});
		}
	</script>

</body>
</html>